### ISSUE TITLE
[Cinnamon] Mint-Y GTK theme > rounded corners on window borders are slightly distorted in some cases

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint21-beta#27]
`VirtualBox > Cinnamon install > mintUpdate all up-to-date > Guest additions installed > restarted`

I guess most windows are okay, except some cases:

![mintUpdate-corners](https://user-images.githubusercontent.com/31940713/179090519-d1627189-96f0-45cf-8a28-73a9804e17c9.png)

**Comment by SebastJava** [comment]
Tested on both full installation in VirtualBox and all up-to-date, and also on live USB key

VIRTUALBOX FULL INSTALLATION, ALL UP-TO-DATE:
```
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.19.0.0
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: vmware
    unloaded: fbdev,modesetting,vesa gpu: vmwgfx resolution: 1360x768~60Hz
  OpenGL: renderer: SVGA3D; build: RELEASE; LLVM; v: 2.1 Mesa 22.0.1
```

LIVE USB 2.0 KEY:
```
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    driver: i915 v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 2000 (SNB GT1)
    v: 3.3 Mesa 22.0.1
```
