### ISSUE TITLE
Shadows around some windows: flashing when mouse hover

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint21-beta#35]
### on VirtualBox:

https://user-images.githubusercontent.com/31940713/179120823-59a0be09-17bd-42cb-b07e-475eb5701e77.mp4

VirtualBox > Cinnamon install > mintUpdate all up-to-date > Guest additions installed > restarted:
```
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.19.0.0
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: vmware
    unloaded: fbdev,modesetting,vesa gpu: vmwgfx resolution: 1360x768~60Hz
  OpenGL: renderer: SVGA3D; build: RELEASE; LLVM; v: 2.1 Mesa 22.0.1
```
### on live USB 2.0:

[window-shadow-flashing-2022-07-14_23.12.59.webm](https://user-images.githubusercontent.com/31940713/179120855-58654967-2da4-4869-9ebe-66e3a19ad2eb.webm)

Also tested on a live USB 2.0. Not exactly the same, but some kind of weird flash there too:
```
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    driver: i915 v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 2000 (SNB GT1)
    v: 3.3 Mesa 22.0.1
```

**Additional info**
* Currently on Cinnamon 20.3: no bug
* Tested on live USB 2.0 with the old Cinnamon 20.3: no bug
* It wasn't as bad on the live USB 2.0. Maybe it is not perfect just because the USB is slow !? I am not sure...
